### PR TITLE
 nav.css

### PR DESCRIPTION
**Pull request by kushaljgec2025**
merge it plss . nav  portion chnaged

### CODE REVIEW

**Comment by gg-developer** [comment]
> merge it plss . nav portion chnaged

Can you send a screenshot of your changes

**Comment by kushaljgec2025** [comment]
Screenshot 2022-10-30 192326

**Comment by kushaljgec2025** [comment]
plss merge it sir @gg-developer

**Comment by gg-developer** [comment]
Thanks for Contributing.

**Pull request merged**
